TEMPLATEROOT = ../../lib/STM32F1-Template-HAL

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g 

# object files

OBJS=  $(STARTUP) main.o stm32f1xx_it.o stm32f1xx_hal.o stm32f1xx_hal_rcc.o stm32f1xx_hal_gpio.o stm32f1xx_hal_cortex.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common


